version: '3.3'

services:
  mongo_db:
    image: mongo
    container_name: mongo
    environment:
    - MONGO_INITDB_ROOT_USERNAME=admin
    - MONGO_INITDB_ROOT_PASSWORD=password
    restart: always
    ports:
      - 27017:27017